language: python
python:
  - "3.5"
# use system packages in virtualenv
virtualenv:
  system_site_packages: false
# apt packages
addons:
  apt:
    packages:
    - libxml2-dev
    - libxslt1-dev
    - python-dev
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade asq"
  - "pip install --upgrade lxml"
  - "pip install --upgrade PyQt5"
  - "pip install git+https://github.com/OpenNingia/l5rcm-data-access.git@develop"
  - "pip install --no-deps ./l5r"
# command to run tests
script: nosetests

before_deploy:
  - "cd tools/deploy/linux"
  - "./makedeb.sh"

deploy:
  provider: releases
  api_key: "e5ebc2ddf8d3d2645afa708ccb9e828846d1e932"
  file: "tools/deploy/linux/*.deb"
  skip_cleanup: true
  on:
    branch: feature/python3_pyqt5  