language: python
python:
- '3.6'
cache: pip
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - librsvg2-bin
    - python-docutils
    - fakeroot

install:
- pip install --upgrade pip
- pip install --upgrade asq
- pip install --upgrade lxml
- pip install --upgrade PyQt5
- pip install git+https://github.com/OpenNingia/l5rcm-data-access.git@develop
- pip install --no-deps ./l5r
script: nosetests
after_success:
- 'export APP_VER_LN=$(grep -n ''^APP_VERSION\s*=\s*'' l5r/l5rcmcore/__init__.py |
  cut -d\: -f1)'
- export APP_VER_BS=$(grep '^APP_VERSION\s*=\s*' l5r/l5rcmcore/__init__.py | cut -d\.
  -f1,2)
- echo $APP_VER_BS
- export APP_VER_NW=$APP_VER_BS.$TRAVIS_BUILD_NUMBER
- echo $APP_VER_NW
- sed -i "${APP_VER_LN}s/.*/${APP_VER_NW}'/" l5r/l5rcmcore/__init__.py
- grep -n '^APP_VERSION\s*=\s*' l5r/l5rcmcore/__init__.py
- cd tools/deploy/linux
- "./makedeb.sh"
- export RELEASE_PKG_FILE=$(ls *.deb)
- echo $RELEASE_PKG_FILE
deploy:
  provider: releases
  api_key:
    secure: BkhDZEBo1u1PK74EWPO5yrP4hnVG2mM8qNfwI18lysZZBGE8YtIQQjYRBVwl1j3WElZ+1fxSJ5EYT8BeE+xKXn4G8scpkk8xAWMUBO23GiPQ/5xbl3vWPVqRqRCiL6pTeXfDF14uX69mLlTKTgPBFDh1WXyR8tiZmqQL1wEUheNis7FqLj/hq/SJEMmu+t6PdtiHbzs5Pue4KR14Pr6igeRrSs2vrq8Oo8Mv5/CAXxHblfnkQfQILi+IzFGsMCJj7aXKphlD6c1VPNMZ7d7hmOk4iQwIK5I/TbkTKMWBKyr1r+4vEdzQGss8cTYq329WIcMdybCbp6eOoF+7mu2FmPObXWiS47NT6mEPTWwFLg6KWB0wX6VeikbYw7C64BSh/XOawcQ801J/dTfbb6it53kMQ1nJ6gb3uRe7TMMqXNoN/zcJnNsmNiC/Nog0WN1V89JlOAgfJFEMuVztt52/69rZlXyFnatG17wnkbYmVSt6gohcTVCUEcvAI6O8/22T7VD2CQTKNjMHSWcnAwU4pCJNT3Cvv5ZIMYA1aIyNSUujVNjYAEX0exut7Wh65qpGcWl1Atk6yQg89gB9sA5R2V+UXUadw6sDeVqjnnhH+DXTNrfKUSdbS07eed6S2Qc4El63fPi/v/SawEORTfsHI49wq3GO/acju/wav9L97kc=
  skip_cleanup: true
  file: "${TRAVIS_BUILD_DIR}/tools/deploy/linux/${RELEASE_PKG_FILE}"
  on:
    repo: OpenNingia/l5r-character-manager-3
    tags: true
