language: python
sudo: required
python:
  - "2.7"
# set-up ubuntu
before_install:
  - "sudo apt-get update -qq"
# command to install dependencies
install:
  - "sudo apt-get install -y python-pyside"
  - "pip install --upgrade pip"
  - "pip install --upgrade lxml"
  - "pip install --upgrade asq"
  - "pip install --no-deps ./l5r"
# command to run tests
script: nosetests