version: 3.11.{build}

image:
- Visual Studio 2015

init:
  # Gather some basic build environment details.
  - rem set

environment:
  PYTHONVER: 3.5
  PYQTBASEURI: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/
  LXMLBASEURI: http://www.edna-site.org/pub/wheelhouse/
  LXML64: lxml-3.6.0-cp35-cp35m-win_amd64.whl
  LXML32: lxml-3.6.0-cp35-cp35m-win32.whl
  matrix:
    - PYTHONDIR: C:\Python35
    - PYTHONDIR: C:\Python35-x64

install:
  - if %PYTHONDIR:-x64=%==%PYTHONDIR% (set ARCH=x86) else set ARCH=x64
  - if %ARCH%==x86 (set PYQTINSTFILE=PyQt5-5.6-gpl-Py3.5-Qt5.6.0-x32-2.exe) else set PYQTINSTFILE=PyQt5-5.6-gpl-Py3.5-Qt5.6.0-x64-2.exe
  - set PYQTDOWNLOAD=%PYQTBASEURI%%PYQTINSTFILE%
  - if %ARCH%==x86 (set LXMLWHEEL=%LXML32%) else set LXMLWHEEL=%LXML64%
  - set LXMLDOWNLOAD=%LXMLBASEURI%%LXMLWHEEL%
  - set PATH=%PYTHONDIR%;%PYTHONDIR%\scripts;%PATH%    
  - ps: Start-FileDownload $env:LXMLDOWNLOAD
  - pip3 install %LXMLWHEEL%
  - pip3 install --upgrade asq  
  - pip3 install --upgrade PyQt5 
  - pip install git+https://github.com/OpenNingia/l5rcm-data-access.git@feature/python3

build_script:
  - pip install --no-deps .\l5r
  - nosetests

# fetch repository as zip archive
shallow_clone: true
