version: 3.11.{build}

image:
- Visual Studio 2015

init:
  # Gather some basic build environment details.
  - rem set
  - dir

environment:
  PYTHONVER: 3.6
  matrix:
    - PYTHONDIR: C:\Python36
    - PYTHONDIR: C:\Python36-x64

install:
  - if %PYTHONDIR:-x64=%==%PYTHONDIR% (set ARCH=x86) else set ARCH=x64
  - choco install -y InnoSetup
  - set PATH=%PYTHONDIR%;%PYTHONDIR%\scripts;C:\Program Files (x86)\Inno Setup 5;%PATH%
  - python --version
  - echo %PATH%
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install cx_Freeze
  - pip install --upgrade nose
  - pip install git+https://github.com/OpenNingia/l5rcm-data-access.git@develop

build_script:
  - pip install --no-deps .\l5r
  - nosetests

after_build:
  - mkdir tools\deploy\windows\dist
  - python cxfreeze.py build
  - cd tools\deploy\windows\
  - deploy_common.bat
  - dir common
  - dir dist
  - ISCC setup_appveyor.iss

artifacts:
  - path: tools\deploy\windows\Output\l5rcm-setup.exe

# fetch repository as zip archive
shallow_clone: true
